#*****eureka的配置*******
eureka:
  client:
    serviceUrl:
#      defaultZone: http://${cluster.node1.hostname}:${cluster.node1.port}/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/
#    禁止eureka-server注册成客户端,搭建集群不能开启(写)该功能。
    register-with-eureka: false
  server:
#  eureka的自我保护机制：开发环境开启，生产环境关闭
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
#*****项目常用配置********
spring:
  application:
    name: eureka1
#*****项目常用配置********
server:
  port: 8761
#*****自定义配置：用于配置eureka集群搭建的注册中心**********
cluster:
  node1:
    hostname: 127.0.0.1
    port: 8761
  node2:
    hostname: 127.0.0.1
    port: 8762
  node3:
    hostname: 127.0.0.1
    port: 8763